### ISSUE TITLE
This plugin doesn't verify authenticated user is within the Google Apps domain.

### ISSUE THREAD

**Issue by nov** [recampbell/google-login#10]
If I remove `hd` request parameter, this plugin allows non-Google Apps users to login.
You should verify given email address belongs to the Google Apps domain.

Since I'm not familiar with Java, it's a bit hard for me to make a pull request, but what you should do is basically
- add `openid` to the scope list (which triggers OpenID Connect feature described below)
- get `id_token` from token endpoint along with `access_token`
- parse the `id_token` using a JSON Web Token library (JWT signature verification in code flow is OPTIONAL, not REQUIRED)
- verify `hd` included in the `id_token` matches what your plugin sent

ps.
If you support multiple Google Apps domains, you'll need to bind the sent `hd` param to the `state` param.

**Comment by kuahyeow** [comment]
@recampbell This sounds like an issue that needs to be given more attention. It's almost a security issue if an un-authorised person can login with any gmail address just by manipulating a client side query parameter.

**Comment by nov** [comment]
I've just noticed this issue had been fixed in the other repo with better java code.
thanks!
