### ISSUE TITLE
is there a way to disable the plugin?

### ISSUE THREAD

**Issue by t-readyroc** [recampbell/google-login#21]
We're currently unable to login to our Jenkins server, because the Google API credential configured in the plugin has somehow disappeared.

I've touched the google-login.jpi.disabled file, but Jenkins then throws an error on startup. Is there a way to disable the plugin so that we can login & change the plugin config? Or is there a way to directly reconfig via the db somehow?

**Comment by t-readyroc** [comment]
Figured out that I could disable security from config.xml.

**Comment by LINK209** [comment]
I need hack domain
