### ISSUE TITLE
Cant logout

### ISSUE THREAD

**Issue by markunsworth** [recampbell/google-login#7]
When I click the logout button I just get returned to the dashboard in the logged in state. I'm assuming it hits the homepage which forces back through the Google login, which is still approved and hence i'm not logged out.

Is it possible to revert the token via the Google API when clicking logout?

**Comment by raags** [comment]
I guess this also causes the auto logout to not work. I want to force users to logout after 1 day, but with this plugin, users are always logged in. Can this behaviour be changed? i.e force google login access page again? This is how gerrit Oauth plugin is also implemented : https://github.com/davido/gerrit-oauth-provider

**Comment by jinahya** [comment]
+1

**Comment by jknightstreamme** [comment]
+1
